apiVersion: v1
kind: PersistentVolume 
metadata:
  name: mysql-pv-volume
  labels:
    type: local
    tier: database
spec:
  storageclassName: manual
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    "/mnt/data"
