apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  tier: database
spec:
  storageclassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    request:
      storage: 2Gi